### Cho dữ liệu play golf trong tập tin playgoft_data.xlsx.
### Yêu cầu: Hãy đọc dữ liệu từ tập tin này, áp dụng Naive Bayes để thực hiện việc xác định có đi chơi golf hay không dựa trên các thông tin như: 'Outlook', 'Temperature', 'Humidity', 'Wind', 'Play Golf'
### Yêu cầu:
1. Hãy chuẩn hóa dữ liệu cho phù hợp
2. Áp dụng Naive Bayes. Tìm kết quả
3. Kiểm tra độ chính xác
4. Xuất/ghi model
5. Đọc model
6. Cho dữ liệu Test: X_test = [["Overcast", "Cool", "High", "Strong"], ["Sunny", "Cool", "High","Weak"]] => Y_test

In [1]:
import pandas as pd
import numpy as np
# Xuất model
import pickle

from sklearn.preprocessing import LabelEncoder
from sklearn.utils.validation import column_or_1d
# Sử dụng BernoulliNB
from sklearn.naive_bayes import BernoulliNB

In [2]:
df = pd.read_excel('../../Data/playgolf_data.xlsx',engine='openpyxl', index_col = 0)
df.head()

      Outlook Temperature Humidity    Wind Play Golf
Day
1       Sunny         Hot     High    Weak        No
2       Sunny         Hot     High  Strong        No
3    Overcast         Hot     High    Weak       Yes
4        Rain        Mild     High    Weak       Yes
5        Rain        Cool   Normal    Weak       Yes

In [3]:
features = df.drop("Play Golf", axis=1)
target = df[["Play Golf"]]

In [4]:
features = pd.get_dummies(features)
features

,Outlook_Overcast,Outlook_Rain,Outlook_Sunny,Temperature_Cool,Temperature_Hot,Temperature_Mild,Humidity_High,Humidity_Normal,Wind_Strong,Wind_Weak
Day,,,,,,,,,,
1,0,0,1,0,1,0,1,0,0,1
2,0,0,1,0,1,0,1,0,1,0
3,1,0,0,0,1,0,1,0,0,1
4,0,1,0,0,0,1,1,0,0,1
5,0,1,0,1,0,0,0,1,0,1
6,0,1,0,1,0,0,0,1,1,0
7,1,0,0,1,0,0,0,1,1,0
8,0,0,1,0,0,1,1,0,0,1
9,0,0,1,1,0,0,0,1,0,1
10,0,1,0,0,0,1,0,1,0,1
11,0,0,1,0,0,1,0,1,1,0
12,1,0,0,0,0,1,1,0,1,0
13,1,0,0,0,1,0,0,1,0,1
14,0,1,0,0,0,1,1,0,1,0

In [5]:
le = LabelEncoder()
target = le.fit_transform(column_or_1d(target))

In [6]:
model1 = BernoulliNB()
model1.fit(features, target)

BernoulliNB()

In [7]:
# Kiểm tra độ chính xác
print("The prediction accuracy is: ",
model1.score(features,target)*100,"%")

The prediction accuracy is:  92.85714285714286 %

In [8]:
class_names = model1.classes_
class_names

array([0, 1])

In [9]:
# Save to file in the current working directory
pkl_filename = "playgoft_model.pkl"
with open(pkl_filename, 'wb') as file:
    pickle.dump(model1, file)

In [10]:
with open(pkl_filename, 'rb') as file:
    playgoft_model = pickle.load(file)

In [11]:
# Outlook_Overcast Outlook_Rain Outlook_Sunny
# Temperature_Cool Temperature_Hot Temperature_Mild
# Humidity_High Humidity_Normal
# Wind_Strong Wind_Weak
# _________
# X_test = [["Overcast", "Cool", "High", "Strong"],
# ["Sunny", "Cool", "High", "Weak"]]
X_test = [[1, 0, 0, 1, 0, 0, 1, 0, 1, 0], [0, 0, 1, 1, 0, 0, 1, 0, 0, 1]]
y_pred = playgoft_model.predict(X_test)
y_pred

array([1, 0])