In [54]:
import pandas as pd
import ibm_db_dbi

In [55]:
credential = {
  "db": "BLUDB",
  "dsn": "DATABASE=BLUDB;HOSTNAME=dashdb-txn-sbox-yp-dal09-10.services.dal.bluemix.net;PORT=50000;PROTOCOL=TCPIP;UID=rkh34442;PWD=kd2rhlznxp4zw+p5;",
  "host": "dashdb-txn-sbox-yp-dal09-10.services.dal.bluemix.net",
  "hostname": "dashdb-txn-sbox-yp-dal09-10.services.dal.bluemix.net",
  "https_url": "https://dashdb-txn-sbox-yp-dal09-10.services.dal.bluemix.net",
  "jdbcurl": "jdbc:db2://dashdb-txn-sbox-yp-dal09-10.services.dal.bluemix.net:50000/BLUDB",
  "parameters": {
    "role_crn": "crn:v1:bluemix:public:iam::::serviceRole:Manager"
  },
  "password": "kd2rhlznxp4zw+p5",
  "port": 50000,
  "ssldsn": "DATABASE=BLUDB;HOSTNAME=dashdb-txn-sbox-yp-dal09-10.services.dal.bluemix.net;PORT=50001;PROTOCOL=TCPIP;UID=rkh34442;PWD=kd2rhlznxp4zw+p5;Security=SSL;",
  "ssljdbcurl": "jdbc:db2://dashdb-txn-sbox-yp-dal09-10.services.dal.bluemix.net:50001/BLUDB:sslConnection=true;",
  "uri": "db2://rkh34442:kd2rhlznxp4zw%2Bp5@dashdb-txn-sbox-yp-dal09-10.services.dal.bluemix.net:50000/BLUDB",
  "username": "rkh34442"
}

In [56]:
conn = ibm_db_dbi.connect(credential['dsn'], "", "")

In [57]:
sql = 'select * from mcdonalds_nutrition'
df = pd.read_sql(sql, conn)

In [58]:
conn.close()

True

In [59]:
df.shape

(260, 24)

In [60]:
df.head()

,Category,Item,Serving_Size,Calories,Calories_from_Fat,Total_Fat,Total_Fat____Daily_Value_,Saturated_Fat,Saturated_Fat____Daily_Value_,Trans_Fat,...,Carbohydrates,Carbohydrates____Daily_Value_,Dietary_Fiber,Dietary_Fiber____Daily_Value_,Sugars,Protein,Vitamin_A____Daily_Value_,Vitamin_C____Daily_Value_,Calcium____Daily_Value_,Iron____Daily_Value_
0,Breakfast,Egg McMuffin,4.8 oz (136 g),300,120,13.0,20,5.0,25,0.0,...,31,10,4,17,3,17,10,0,25,15
1,Breakfast,Egg White Delight,4.8 oz (135 g),250,70,8.0,12,3.0,15,0.0,...,30,10,4,17,3,18,6,0,25,8
2,Breakfast,Sausage McMuffin,3.9 oz (111 g),370,200,23.0,35,8.0,42,0.0,...,29,10,4,17,2,14,8,0,25,10
3,Breakfast,Sausage McMuffin with Egg,5.7 oz (161 g),450,250,28.0,43,10.0,52,0.0,...,30,10,4,17,2,21,15,0,30,15
4,Breakfast,Sausage McMuffin with Egg Whites,5.7 oz (161 g),400,210,23.0,35,8.0,42,0.0,...,30,10,4,17,2,21,6,0,25,10

In [61]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 260 entries, 0 to 259
Data columns (total 24 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Category                       260 non-null    object
 1   Item                           260 non-null    object
 2   Serving_Size                   260 non-null    object
 3   Calories                       260 non-null    int64
 4   Calories_from_Fat              260 non-null    int64
 5   Total_Fat                      260 non-null    float64
 6   Total_Fat____Daily_Value_      260 non-null    int64
 7   Saturated_Fat                  260 non-null    float64
 8   Saturated_Fat____Daily_Value_  260 non-null    int64
 9   Trans_Fat                      260 non-null    float64
 10  Cholesterol                    260 non-null    int64
 11  Cholesterol____Daily_Value_    260 non-null    int64
 12  Sodium                         260 non-null    int64
 13  Sodium____Daily_Value_         260 non-null    int64
 14  Carbohydrates                  260 non-null    int64
 15  Carbohydrates____Daily_Value_  260 non-null    int64
 16  Dietary_Fiber                  260 non-null    int64
 17  Dietary_Fiber____Daily_Value_  260 non-null    int64
 18  Sugars                         260 non-null    int64
 19  Protein                        260 non-null    int64
 20  Vitamin_A____Daily_Value_      260 non-null    int64
 21  Vitamin_C____Daily_Value_      260 non-null    int64
 22  Calcium____Daily_Value_        260 non-null    int64
 23  Iron____Daily_Value_           260 non-null    int64
dtypes: float64(3), int64(18), object(3)
memory usage: 48.9+ KB

In [62]:
df['Category'].value_counts()

Coffee & Tea          95
Breakfast             42
Smoothies & Shakes    28
Beverages             27
Chicken & Fish        27
Beef & Pork           15
Snacks & Sides        13
Desserts               7
Salads                 6
Name: Category, dtype: int64

In [63]:
df['Serving_Size'].value_counts()

16 fl oz cup       45
12 fl oz cup       38
22 fl oz cup       20
20 fl oz cup       16
30 fl oz cup        7
                   ..
10.1 oz (286 g)     1
11.2 oz (318 g)     1
4 oz (114 g)        1
6.9 oz (197 g)      1
5.4 oz (153 g)      1
Name: Serving_Size, Length: 107, dtype: int64

In [64]:
df.describe()

,Calories,Calories_from_Fat,Total_Fat,Total_Fat____Daily_Value_,Saturated_Fat,Saturated_Fat____Daily_Value_,Trans_Fat,Cholesterol,Cholesterol____Daily_Value_,Sodium,...,Carbohydrates,Carbohydrates____Daily_Value_,Dietary_Fiber,Dietary_Fiber____Daily_Value_,Sugars,Protein,Vitamin_A____Daily_Value_,Vitamin_C____Daily_Value_,Calcium____Daily_Value_,Iron____Daily_Value_
count,260.000000,260.000000,260.000000,260.000000,260.000000,260.000000,260.000000,260.000000,260.000000,260.000000,...,260.000000,260.000000,260.000000,260.000000,260.000000,260.000000,260.000000,260.000000,260.000000,260.000000
mean,368.269231,127.096154,14.165385,21.815385,6.007692,29.965385,0.203846,54.942308,18.392308,495.750000,...,47.346154,15.780769,1.630769,6.530769,29.423077,13.338462,13.426923,8.534615,20.973077,7.734615
std,240.269886,127.875914,14.205998,21.885199,5.321873,26.639209,0.429133,87.269257,29.091653,577.026323,...,28.252232,9.419544,1.567717,6.307057,28.679797,11.426146,24.366381,26.345542,17.019953,8.723263
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,210.000000,20.000000,2.375000,3.750000,1.000000,4.750000,0.000000,5.000000,2.000000,107.500000,...,30.000000,10.000000,0.000000,0.000000,5.750000,4.000000,2.000000,0.000000,6.000000,0.000000
50%,340.000000,100.000000,11.000000,17.000000,5.000000,24.000000,0.000000,35.000000,11.000000,190.000000,...,44.000000,15.000000,1.000000,5.000000,17.500000,12.000000,8.000000,0.000000,20.000000,4.000000
75%,500.000000,200.000000,22.250000,35.000000,10.000000,48.000000,0.000000,65.000000,21.250000,865.000000,...,60.000000,20.000000,3.000000,10.000000,48.000000,19.000000,15.000000,4.000000,30.000000,15.000000
max,1880.000000,1060.000000,118.000000,182.000000,20.000000,102.000000,2.500000,575.000000,192.000000,3600.000000,...,141.000000,47.000000,7.000000,28.000000,128.000000,87.000000,170.000000,240.000000,70.000000,40.000000

In [65]:
df['Calories'].describe()

count     260.000000
mean      368.269231
std       240.269886
min         0.000000
25%       210.000000
50%       340.000000
75%       500.000000
max      1880.000000
Name: Calories, dtype: float64

In [66]:
df[['Calories','Total_Fat']].describe()

          Calories   Total_Fat
count   260.000000  260.000000
mean    368.269231   14.165385
std     240.269886   14.205998
min       0.000000    0.000000
25%     210.000000    2.375000
50%     340.000000   11.000000
75%     500.000000   22.250000
max    1880.000000  118.000000

In [69]:
df.describe(include='all').T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
Category,260,9,Coffee & Tea,95,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Item,260,260,Sweet Tea (Child),1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Serving_Size,260,107,16 fl oz cup,45,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Calories,260,NaN,NaN,NaN,368.269,240.27,0,210,340,500,1880
Calories_from_Fat,260,NaN,NaN,NaN,127.096,127.876,0,20,100,200,1060
Total_Fat,260,NaN,NaN,NaN,14.1654,14.206,0,2.375,11,22.25,118
Total_Fat____Daily_Value_,260,NaN,NaN,NaN,21.8154,21.8852,0,3.75,17,35,182
Saturated_Fat,260,NaN,NaN,NaN,6.00769,5.32187,0,1,5,10,20
Saturated_Fat____Daily_Value_,260,NaN,NaN,NaN,29.9654,26.6392,0,4.75,24,48,102
Trans_Fat,260,NaN,NaN,NaN,0.203846,0.429133,0,0,0,0,2.5
Cholesterol,260,NaN,NaN,NaN,54.9423,87.2693,0,5,35,65,575
Cholesterol____Daily_Value_,260,NaN,NaN,NaN,18.3923,29.0917,0,2,11,21.25,192
Sodium,260,NaN,NaN,NaN,495.75,577.026,0,107.5,190,865,3600
Sodium____Daily_Value_,260,NaN,NaN,NaN,20.6769,24.035,0,4.75,8,36.25,150
Carbohydrates,260,NaN,NaN,NaN,47.3462,28.2522,0,30,44,60,141
Carbohydrates____Daily_Value_,260,NaN,NaN,NaN,15.7808,9.41954,0,10,15,20,47
Dietary_Fiber,260,NaN,NaN,NaN,1.63077,1.56772,0,0,1,3,7
Dietary_Fiber____Daily_Value_,260,NaN,NaN,NaN,6.53077,6.30706,0,0,5,10,28
Sugars,260,NaN,NaN,NaN,29.4231,28.6798,0,5.75,17.5,48,128
Protein,260,NaN,NaN,NaN,13.3385,11.4261,0,4,12,19,87
Vitamin_A____Daily_Value_,260,NaN,NaN,NaN,13.4269,24.3664,0,2,8,15,170
Vitamin_C____Daily_Value_,260,NaN,NaN,NaN,8.53462,26.3455,0,0,0,4,240
Calcium____Daily_Value_,260,NaN,NaN,NaN,20.9731,17.02,0,6,20,30,70
Iron____Daily_Value_,260,NaN,NaN,NaN,7.73462,8.72326,0,0,4,15,40

In [71]:
df.loc[df['Category']=='Breakfast','Sodium'].describe()

count      42.000000
mean     1211.071429
std       509.523373
min       115.000000
25%       892.500000
50%      1265.000000
75%      1477.500000
max      2290.000000
Name: Sodium, dtype: float64

In [72]:
df['Sodium'].max()

3600

In [73]:
df.loc[df['Sodium']==df['Sodium'].max()]

,Category,Item,Serving_Size,Calories,Calories_from_Fat,Total_Fat,Total_Fat____Daily_Value_,Saturated_Fat,Saturated_Fat____Daily_Value_,Trans_Fat,...,Carbohydrates,Carbohydrates____Daily_Value_,Dietary_Fiber,Dietary_Fiber____Daily_Value_,Sugars,Protein,Vitamin_A____Daily_Value_,Vitamin_C____Daily_Value_,Calcium____Daily_Value_,Iron____Daily_Value_
82,Chicken & Fish,Chicken McNuggets (40 piece),22.8 oz (646 g),1880,1060,118.0,182,20.0,101,1.0,...,118,39,6,24,1,87,0,15,8,25